version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-attendance
    ports:
      - "5042:5432"
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pg_attendance_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-attendance
    ports:
      - "3042:3042"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=attendance_db
      - PORT=3042

  employee-attendance:
    build: ./Employee-attendance
    container_name: employee-attendance-ui
    ports:
      - "8060:80"
    depends_on:
      - backend

  hr-attendance:
    build: ./HR-attendance
    container_name: hr-attendance-ui
    ports:
      - "8061:80"
    depends_on:
      - backend

volumes:
  pg_attendance_data:

